import os
import sqlite3

db_dir = r"c:\Users\Surya Narayana\Desktop\visitor management\Data"
if not os.path.exists(db_dir):
    os.makedirs(db_dir)

db_path = os.path.join(db_dir, "VisitorManagement.db")

# Delete old if exists for a fresh schema
if os.path.exists(db_path):
    os.remove(db_path)

conn = sqlite3.connect(db_path)
cur = conn.cursor()

schema = """
CREATE TABLE seq_vms_visitors (id INTEGER PRIMARY KEY AUTOINCREMENT);

CREATE TABLE VMS_MASTER_DEPT (
    DEPT_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    DEPT_NAME VARCHAR(100) NOT NULL,
    IS_ACTIVE INT DEFAULT 1
);

CREATE TABLE VMS_MASTER_IDPROOF (
    IDPROOF_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    PROOF_NAME VARCHAR(100) NOT NULL,
    IS_ACTIVE INT DEFAULT 1
);

CREATE TABLE VMS_MASTER_HOST (
    HOST_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    HOST_NAME VARCHAR(150) NOT NULL,
    DEPT_ID INT REFERENCES VMS_MASTER_DEPT(DEPT_ID),
    EMAIL VARCHAR(150),
    MOBILE VARCHAR(15),
    IS_ACTIVE INT DEFAULT 1
);

CREATE TABLE VMS_MASTER_GATE (
    GATE_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    GATE_NUMBER VARCHAR(50) NOT NULL,
    IS_ACTIVE INT DEFAULT 1
);

CREATE TABLE VMS_USERS (
    USER_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    USERNAME VARCHAR(100) UNIQUE NOT NULL,
    PASSWORD_HASH VARCHAR(256) NOT NULL,
    FULL_NAME VARCHAR(150) NOT NULL,
    ROLE VARCHAR(20) NOT NULL CHECK (ROLE IN ('USER', 'GUARD', 'ADMIN')),
    IS_ACTIVE INT DEFAULT 1,
    CREATED_DATE DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE VMS_VISITORS (
    VISITOR_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    VISIT_TOKEN VARCHAR(50) UNIQUE NOT NULL,
    FULL_NAME VARCHAR(150) NOT NULL,
    MOBILE VARCHAR(15) NOT NULL,
    EMAIL VARCHAR(150),
    COMPANY_NAME VARCHAR(150),
    PURPOSE VARCHAR(500) NOT NULL,
    HOST_ID INT REFERENCES VMS_MASTER_HOST(HOST_ID),
    DEPT_ID INT REFERENCES VMS_MASTER_DEPT(DEPT_ID),
    EXPECTED_DATETIME DATETIME NOT NULL,
    IDPROOF_TYPE_ID INT REFERENCES VMS_MASTER_IDPROOF(IDPROOF_ID),
    IDPROOF_NUMBER VARCHAR(50) NOT NULL,
    STATUS VARCHAR(20) DEFAULT 'Pending' CHECK (STATUS IN ('Pending', 'Approved', 'Checked-In', 'Checked-Out', 'Cancelled')),
    REGISTERED_BY INT REFERENCES VMS_USERS(USER_ID),
    CREATED_DATE DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE VMS_FILE_UPLOADS (
    FILE_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    VISITOR_ID INT REFERENCES VMS_VISITORS(VISITOR_ID),
    UPLOAD_TYPE VARCHAR(50) CHECK (UPLOAD_TYPE IN ('Photo', 'IDProof')),
    ORIGINAL_NAME VARCHAR(255) NOT NULL,
    STORED_NAME VARCHAR(255) NOT NULL, 
    FILE_PATH VARCHAR(1000) NOT NULL,
    FILE_URL VARCHAR(1000) NOT NULL,
    FILE_SIZE_BYTES INTEGER,
    MIME_TYPE VARCHAR(50),
    UPLOADED_DATE DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE VMS_CHECKIN_LOG (
    LOG_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    VISITOR_ID INT REFERENCES VMS_VISITORS(VISITOR_ID),
    GATE_ID INT REFERENCES VMS_MASTER_GATE(GATE_ID),
    GUARD_ID INT REFERENCES VMS_USERS(USER_ID),
    CHECKIN_TIME DATETIME NOT NULL,
    CHECKOUT_TIME DATETIME,
    DURATION_MINUTES INT
);

CREATE VIEW VW_VISITOR_FULL_DETAIL AS
SELECT 
    v.VISITOR_ID, v.VISIT_TOKEN, v.FULL_NAME, v.MOBILE, v.EMAIL, v.COMPANY_NAME, v.PURPOSE,
    v.EXPECTED_DATETIME, v.STATUS, v.IDPROOF_NUMBER,
    h.HOST_NAME, d.DEPT_NAME, p.PROOF_NAME as IDPROOF_TYPE,
    (SELECT FILE_URL FROM VMS_FILE_UPLOADS f WHERE f.VISITOR_ID = v.VISITOR_ID AND f.UPLOAD_TYPE = 'Photo' LIMIT 1) AS PHOTO_URL,
    (SELECT FILE_URL FROM VMS_FILE_UPLOADS f WHERE f.VISITOR_ID = v.VISITOR_ID AND f.UPLOAD_TYPE = 'IDProof' LIMIT 1) AS IDPROOF_URL,
    u.FULL_NAME AS REGISTERED_BY_NAME,
    v.DEPT_ID
FROM VMS_VISITORS v
LEFT JOIN VMS_MASTER_HOST h ON v.HOST_ID = h.HOST_ID
LEFT JOIN VMS_MASTER_DEPT d ON v.DEPT_ID = d.DEPT_ID
LEFT JOIN VMS_MASTER_IDPROOF p ON v.IDPROOF_TYPE_ID = p.IDPROOF_ID
LEFT JOIN VMS_USERS u ON v.REGISTERED_BY = u.USER_ID;
"""

try:
    cur.executescript(schema)
    conn.commit()
    print("Schema created.")
except Exception as e:
    print("Schema error:", e)

import hashlib
password_hash = hashlib.sha256(b'Surya@189489').hexdigest()
admin_no = '8142027323'

try:
    cur.execute("INSERT INTO VMS_USERS (USERNAME, PASSWORD_HASH, FULL_NAME, ROLE, IS_ACTIVE) VALUES (?, ?, 'System Administrator', 'ADMIN', 1)", (admin_no, password_hash))
    conn.commit()
    print("Admin inserted successfully.")
except Exception as e:
    print("Admin insert error:", e)

conn.close()
