-- ==========================================================
-- VISITOR MANAGEMENT SYSTEM (VMS) - Oracle 19c Schema
-- ==========================================================

-- --------------------------------------------------------
-- 1. SEQUENCES
-- --------------------------------------------------------
CREATE SEQUENCE SEQ_VMS_USERS START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_VMS_VISITORS START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_VMS_FILE_UPLOADS START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_VMS_CHECKIN_LOG START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_VMS_AUDIT_LOG START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_VMS_MASTER_DEPT START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_VMS_MASTER_IDPROOF START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_VMS_MASTER_HOST START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_VMS_MASTER_GATE START WITH 1 INCREMENT BY 1 NOCACHE;

-- --------------------------------------------------------
-- 2. MASTER TABLES
-- --------------------------------------------------------
CREATE TABLE VMS_MASTER_DEPT (
    DEPT_ID NUMBER PRIMARY KEY,
    DEPT_NAME VARCHAR2(100) NOT NULL,
    IS_ACTIVE NUMBER(1) DEFAULT 1
);

CREATE TABLE VMS_MASTER_IDPROOF (
    IDPROOF_ID NUMBER PRIMARY KEY,
    PROOF_NAME VARCHAR2(100) NOT NULL, -- Aadhar, Passport, DL, VoterID
    IS_ACTIVE NUMBER(1) DEFAULT 1
);

CREATE TABLE VMS_MASTER_HOST (
    HOST_ID NUMBER PRIMARY KEY,
    HOST_NAME VARCHAR2(150) NOT NULL,
    DEPT_ID NUMBER REFERENCES VMS_MASTER_DEPT(DEPT_ID),
    EMAIL VARCHAR2(150),
    MOBILE VARCHAR2(15),
    IS_ACTIVE NUMBER(1) DEFAULT 1
);

CREATE TABLE VMS_MASTER_GATE (
    GATE_ID NUMBER PRIMARY KEY,
    GATE_NUMBER VARCHAR2(50) NOT NULL,
    IS_ACTIVE NUMBER(1) DEFAULT 1
);

-- --------------------------------------------------------
-- 3. CORE TABLES
-- --------------------------------------------------------
CREATE TABLE VMS_USERS (
    USER_ID NUMBER PRIMARY KEY,
    USERNAME VARCHAR2(100) UNIQUE NOT NULL,
    PASSWORD_HASH VARCHAR2(256) NOT NULL, -- SHA256
    FULL_NAME VARCHAR2(150) NOT NULL,
    ROLE VARCHAR2(20) NOT NULL CHECK (ROLE IN ('USER', 'GUARD', 'ADMIN')),
    IS_ACTIVE NUMBER(1) DEFAULT 1,
    CREATED_DATE TIMESTAMP DEFAULT SYSTIMESTAMP
);

CREATE TABLE VMS_VISITORS (
    VISITOR_ID NUMBER PRIMARY KEY,
    VISIT_TOKEN VARCHAR2(50) UNIQUE NOT NULL, -- Format: VMS-YYYYMMDD-XXXX
    FULL_NAME VARCHAR2(150) NOT NULL,
    MOBILE VARCHAR2(15) NOT NULL,
    EMAIL VARCHAR2(150),
    COMPANY_NAME VARCHAR2(150),
    PURPOSE VARCHAR2(500) NOT NULL,
    HOST_ID NUMBER REFERENCES VMS_MASTER_HOST(HOST_ID),
    DEPT_ID NUMBER REFERENCES VMS_MASTER_DEPT(DEPT_ID),
    EXPECTED_DATETIME TIMESTAMP NOT NULL,
    IDPROOF_TYPE_ID NUMBER REFERENCES VMS_MASTER_IDPROOF(IDPROOF_ID),
    IDPROOF_NUMBER VARCHAR2(50) NOT NULL,
    STATUS VARCHAR2(20) DEFAULT 'Pending' CHECK (STATUS IN ('Pending', 'Approved', 'Checked-In', 'Checked-Out', 'Cancelled')),
    REGISTERED_BY NUMBER REFERENCES VMS_USERS(USER_ID),
    CREATED_DATE TIMESTAMP DEFAULT SYSTIMESTAMP
);

CREATE TABLE VMS_FILE_UPLOADS (
    FILE_ID NUMBER PRIMARY KEY,
    VISITOR_ID NUMBER REFERENCES VMS_VISITORS(VISITOR_ID),
    UPLOAD_TYPE VARCHAR2(50) CHECK (UPLOAD_TYPE IN ('Photo', 'IDProof')),
    ORIGINAL_NAME VARCHAR2(255) NOT NULL,
    STORED_NAME VARCHAR2(255) NOT NULL, -- GUID + Ext
    FILE_PATH VARCHAR2(1000) NOT NULL,
    FILE_URL VARCHAR2(1000) NOT NULL,
    FILE_SIZE_BYTES NUMBER,
    MIME_TYPE VARCHAR2(50),
    UPLOADED_DATE TIMESTAMP DEFAULT SYSTIMESTAMP
);

CREATE TABLE VMS_CHECKIN_LOG (
    LOG_ID NUMBER PRIMARY KEY,
    VISITOR_ID NUMBER REFERENCES VMS_VISITORS(VISITOR_ID),
    GATE_ID NUMBER REFERENCES VMS_MASTER_GATE(GATE_ID),
    GUARD_ID NUMBER REFERENCES VMS_USERS(USER_ID),
    CHECKIN_TIME TIMESTAMP NOT NULL,
    CHECKOUT_TIME TIMESTAMP,
    DURATION_MINUTES NUMBER
);

CREATE TABLE VMS_AUDIT_LOG (
    AUDIT_ID NUMBER PRIMARY KEY,
    USER_ID NUMBER REFERENCES VMS_USERS(USER_ID),
    ACTION_TYPE VARCHAR2(100) NOT NULL, -- Login, Register, Check-In, Check-Out, etc.
    ENTITY_NAME VARCHAR2(100),
    ENTITY_ID NUMBER,
    IP_ADDRESS VARCHAR2(50),
    ACTION_TIME TIMESTAMP DEFAULT SYSTIMESTAMP,
    DETAILS CLOB
);

-- --------------------------------------------------------
-- 4. VIEWS
-- --------------------------------------------------------

CREATE OR REPLACE VIEW VW_VISITOR_FULL_DETAIL AS
SELECT 
    v.VISITOR_ID, v.VISIT_TOKEN, v.FULL_NAME, v.MOBILE, v.EMAIL, v.COMPANY_NAME, v.PURPOSE,
    v.EXPECTED_DATETIME, v.STATUS, v.IDPROOF_NUMBER,
    h.HOST_NAME, d.DEPT_NAME, p.PROOF_NAME as IDPROOF_TYPE,
    (SELECT FILE_URL FROM VMS_FILE_UPLOADS f WHERE f.VISITOR_ID = v.VISITOR_ID AND f.UPLOAD_TYPE = 'Photo' AND ROWNUM = 1) AS PHOTO_URL,
    (SELECT FILE_URL FROM VMS_FILE_UPLOADS f WHERE f.VISITOR_ID = v.VISITOR_ID AND f.UPLOAD_TYPE = 'IDProof' AND ROWNUM = 1) AS IDPROOF_URL,
    u.FULL_NAME AS REGISTERED_BY_NAME
FROM VMS_VISITORS v
LEFT JOIN VMS_MASTER_HOST h ON v.HOST_ID = h.HOST_ID
LEFT JOIN VMS_MASTER_DEPT d ON v.DEPT_ID = d.DEPT_ID
LEFT JOIN VMS_MASTER_IDPROOF p ON v.IDPROOF_TYPE_ID = p.IDPROOF_ID
LEFT JOIN VMS_USERS u ON v.REGISTERED_BY = u.USER_ID;

CREATE OR REPLACE VIEW VW_TODAY_VISITORS AS
SELECT * FROM VW_VISITOR_FULL_DETAIL
WHERE TRUNC(EXPECTED_DATETIME) = TRUNC(SYSDATE);

CREATE OR REPLACE VIEW VW_ACTIVE_VISITORS AS
SELECT * FROM VW_VISITOR_FULL_DETAIL
WHERE STATUS = 'Checked-In';

-- --------------------------------------------------------
-- 5. STORED PROCEDURES
-- --------------------------------------------------------

CREATE OR REPLACE PROCEDURE SP_REGISTER_VISITOR (
    p_FULL_NAME IN VARCHAR2,
    p_MOBILE IN VARCHAR2,
    p_EMAIL IN VARCHAR2,
    p_COMPANY_NAME IN VARCHAR2,
    p_PURPOSE IN VARCHAR2,
    p_HOST_ID IN NUMBER,
    p_DEPT_ID IN NUMBER,
    p_EXPECTED_DATETIME IN TIMESTAMP,
    p_IDPROOF_TYPE_ID IN NUMBER,
    p_IDPROOF_NUMBER IN VARCHAR2,
    p_REGISTERED_BY IN NUMBER,
    p_OUT_VISITOR_ID OUT NUMBER,
    p_OUT_TOKEN OUT VARCHAR2
) AS 
    v_seq NUMBER;
BEGIN
    SELECT SEQ_VMS_VISITORS.NEXTVAL INTO v_seq FROM DUAL;
    
    p_OUT_TOKEN := 'VMS-' || TO_CHAR(SYSDATE, 'YYYYMMDD') || '-' || LPAD(v_seq, 4, '0');
    p_OUT_VISITOR_ID := v_seq;

    INSERT INTO VMS_VISITORS (
        VISITOR_ID, VISIT_TOKEN, FULL_NAME, MOBILE, EMAIL, COMPANY_NAME, PURPOSE, 
        HOST_ID, DEPT_ID, EXPECTED_DATETIME, IDPROOF_TYPE_ID, IDPROOF_NUMBER, REGISTERED_BY
    ) VALUES (
        v_seq, p_OUT_TOKEN, p_FULL_NAME, p_MOBILE, p_EMAIL, p_COMPANY_NAME, p_PURPOSE,
        p_HOST_ID, p_DEPT_ID, p_EXPECTED_DATETIME, p_IDPROOF_TYPE_ID, p_IDPROOF_NUMBER, p_REGISTERED_BY
    );
END SP_REGISTER_VISITOR;
/

CREATE OR REPLACE PROCEDURE SP_SAVE_FILE_UPLOAD (
    p_VISITOR_ID IN NUMBER,
    p_UPLOAD_TYPE IN VARCHAR2,
    p_ORIGINAL_NAME IN VARCHAR2,
    p_STORED_NAME IN VARCHAR2,
    p_FILE_PATH IN VARCHAR2,
    p_FILE_URL IN VARCHAR2,
    p_FILE_SIZE_BYTES IN NUMBER,
    p_MIME_TYPE IN VARCHAR2
) AS 
BEGIN
    INSERT INTO VMS_FILE_UPLOADS (
        FILE_ID, VISITOR_ID, UPLOAD_TYPE, ORIGINAL_NAME, STORED_NAME, FILE_PATH, FILE_URL, FILE_SIZE_BYTES, MIME_TYPE
    ) VALUES (
        SEQ_VMS_FILE_UPLOADS.NEXTVAL, p_VISITOR_ID, p_UPLOAD_TYPE, p_ORIGINAL_NAME, p_STORED_NAME, p_FILE_PATH, p_FILE_URL, p_FILE_SIZE_BYTES, p_MIME_TYPE
    );
END SP_SAVE_FILE_UPLOAD;
/

CREATE OR REPLACE PROCEDURE SP_CHECKIN_VISITOR (
    p_VISITOR_ID IN NUMBER,
    p_GATE_ID IN NUMBER,
    p_GUARD_ID IN NUMBER
) AS 
BEGIN
    UPDATE VMS_VISITORS SET STATUS = 'Checked-In' WHERE VISITOR_ID = p_VISITOR_ID;
    
    INSERT INTO VMS_CHECKIN_LOG (
        LOG_ID, VISITOR_ID, GATE_ID, GUARD_ID, CHECKIN_TIME
    ) VALUES (
        SEQ_VMS_CHECKIN_LOG.NEXTVAL, p_VISITOR_ID, p_GATE_ID, p_GUARD_ID, SYSTIMESTAMP
    );
END SP_CHECKIN_VISITOR;
/

CREATE OR REPLACE PROCEDURE SP_CHECKOUT_VISITOR (
    p_VISITOR_ID IN NUMBER
) AS 
    v_log_id NUMBER;
    v_checkin_time TIMESTAMP;
    v_duration NUMBER;
BEGIN
    UPDATE VMS_VISITORS SET STATUS = 'Checked-Out' WHERE VISITOR_ID = p_VISITOR_ID;
    
    -- Find latest check-in
    SELECT LOG_ID, CHECKIN_TIME INTO v_log_id, v_checkin_time 
    FROM VMS_CHECKIN_LOG 
    WHERE VISITOR_ID = p_VISITOR_ID AND CHECKOUT_TIME IS NULL 
    ORDER BY CHECKIN_TIME DESC FETCH FIRST 1 ROWS ONLY;

    -- Update checkout and duration
    v_duration := EXTRACT(DAY FROM (SYSTIMESTAMP - v_checkin_time)) * 24 * 60 + 
                  EXTRACT(HOUR FROM (SYSTIMESTAMP - v_checkin_time)) * 60 + 
                  EXTRACT(MINUTE FROM (SYSTIMESTAMP - v_checkin_time));

    UPDATE VMS_CHECKIN_LOG 
    SET CHECKOUT_TIME = SYSTIMESTAMP, DURATION_MINUTES = v_duration
    WHERE LOG_ID = v_log_id;
END SP_CHECKOUT_VISITOR;
/

CREATE OR REPLACE PROCEDURE SP_GET_DASHBOARD_COUNTS (
    p_TODAY_EXPECTED OUT NUMBER,
    p_CHECKED_IN OUT NUMBER,
    p_CHECKED_OUT OUT NUMBER,
    p_PENDING OUT NUMBER,
    p_MONTH_REGISTERED OUT NUMBER
) AS
BEGIN
    SELECT COUNT(*) INTO p_TODAY_EXPECTED FROM VMS_VISITORS WHERE TRUNC(EXPECTED_DATETIME) = TRUNC(SYSDATE);
    SELECT COUNT(*) INTO p_CHECKED_IN FROM VMS_VISITORS WHERE STATUS = 'Checked-In';
    SELECT COUNT(*) INTO p_CHECKED_OUT FROM VMS_VISITORS WHERE TRUNC(EXPECTED_DATETIME) = TRUNC(SYSDATE) AND STATUS = 'Checked-Out';
    SELECT COUNT(*) INTO p_PENDING FROM VMS_VISITORS WHERE STATUS = 'Pending';
    SELECT COUNT(*) INTO p_MONTH_REGISTERED FROM VMS_VISITORS WHERE TRUNC(CREATED_DATE, 'MM') = TRUNC(SYSDATE, 'MM');
END SP_GET_DASHBOARD_COUNTS;
/

-- Sample Report Procdure (using SYS_REFCURSOR for ADO.NET)
CREATE OR REPLACE PROCEDURE SP_GET_VISITOR_REPORT (
    p_START_DATE IN DATE,
    p_END_DATE IN DATE,
    p_DEPT_ID IN NUMBER,
    p_RECORDSET OUT SYS_REFCURSOR
) AS 
BEGIN
    OPEN p_RECORDSET FOR 
    SELECT * FROM VW_VISITOR_FULL_DETAIL 
    WHERE TRUNC(EXPECTED_DATETIME) >= p_START_DATE 
      AND TRUNC(EXPECTED_DATETIME) <= p_END_DATE
      AND (p_DEPT_ID = 0 OR DEPT_ID = p_DEPT_ID);
END SP_GET_VISITOR_REPORT;
/

CREATE OR REPLACE PROCEDURE SP_AUTHENTICATE_USER (
    p_USERNAME IN VARCHAR2,
    p_PASSWORD_HASH IN VARCHAR2,
    p_RECORDSET OUT SYS_REFCURSOR
) AS 
BEGIN
    OPEN p_RECORDSET FOR 
    SELECT USER_ID, USERNAME, FULL_NAME, ROLE, IS_ACTIVE 
    FROM VMS_USERS 
    WHERE USERNAME = p_USERNAME AND PASSWORD_HASH = p_PASSWORD_HASH;
END SP_AUTHENTICATE_USER;
/

CREATE OR REPLACE PROCEDURE SP_SET_GUARD_PASSWORD (
    p_EMP_NO IN VARCHAR2,
    p_PASSWORD_HASH IN VARCHAR2,
    p_OUT_STATUS OUT NUMBER 
) AS 
    v_count NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_count FROM VMS_USERS WHERE USERNAME = p_EMP_NO AND ROLE = 'GUARD';
    
    IF v_count > 0 THEN
        UPDATE VMS_USERS SET PASSWORD_HASH = p_PASSWORD_HASH WHERE USERNAME = p_EMP_NO AND ROLE = 'GUARD';
        p_OUT_STATUS := 1; -- Success
    ELSE
        -- Optionally auto-create the guard if not exists, but for now we just fail if employee doesn't correspond to a guard account
        p_OUT_STATUS := 0; -- Not Found
    END IF;
END SP_SET_GUARD_PASSWORD;
/

-- --------------------------------------------------------
-- 6. SEED DATA
-- --------------------------------------------------------
-- Create a default admin user. Password is 'admin123'
-- Hash computed using SHA-256 for 'admin123' is:
-- 240be518fabd2724ddb6f04eeb1da5967448d7e831c08c8fa822809f74c720a9
INSERT INTO VMS_USERS (USER_ID, USERNAME, PASSWORD_HASH, FULL_NAME, ROLE, IS_ACTIVE)
SELECT 1, 'ADMIN_01', '240be518fabd2724ddb6f04eeb1da5967448d7e831c08c8fa822809f74c720a9', 'System Administrator', 'ADMIN', 1 
FROM DUAL 
WHERE NOT EXISTS (SELECT 1 FROM VMS_USERS WHERE USERNAME = 'ADMIN_01');

COMMIT;

