-- ==========================================================
-- VISITOR MANAGEMENT SYSTEM (VMS) - PostgreSQL Schema
-- ==========================================================

-- --------------------------------------------------------
-- 1. SEQUENCES (PostgreSQL uses SERIAL, but we keep this for backwards compatibility where manually queried)
-- --------------------------------------------------------
CREATE SEQUENCE seq_vms_visitors START 1;

-- --------------------------------------------------------
-- 2. MASTER TABLES
-- --------------------------------------------------------
CREATE TABLE VMS_MASTER_DEPT (
    DEPT_ID SERIAL PRIMARY KEY,
    DEPT_NAME VARCHAR(100) NOT NULL,
    IS_ACTIVE INT DEFAULT 1
);

CREATE TABLE VMS_MASTER_IDPROOF (
    IDPROOF_ID SERIAL PRIMARY KEY,
    PROOF_NAME VARCHAR(100) NOT NULL,
    IS_ACTIVE INT DEFAULT 1
);

CREATE TABLE VMS_MASTER_HOST (
    HOST_ID SERIAL PRIMARY KEY,
    HOST_NAME VARCHAR(150) NOT NULL,
    DEPT_ID INT REFERENCES VMS_MASTER_DEPT(DEPT_ID),
    EMAIL VARCHAR(150),
    MOBILE VARCHAR(15),
    IS_ACTIVE INT DEFAULT 1
);

CREATE TABLE VMS_MASTER_GATE (
    GATE_ID SERIAL PRIMARY KEY,
    GATE_NUMBER VARCHAR(50) NOT NULL,
    IS_ACTIVE INT DEFAULT 1
);

-- --------------------------------------------------------
-- 3. CORE TABLES
-- --------------------------------------------------------
CREATE TABLE VMS_USERS (
    USER_ID SERIAL PRIMARY KEY,
    USERNAME VARCHAR(100) UNIQUE NOT NULL,
    PASSWORD_HASH VARCHAR(256) NOT NULL,
    FULL_NAME VARCHAR(150) NOT NULL,
    ROLE VARCHAR(20) NOT NULL CHECK (ROLE IN ('USER', 'GUARD', 'ADMIN')),
    IS_ACTIVE INT DEFAULT 1,
    CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE VMS_VISITORS (
    VISITOR_ID SERIAL PRIMARY KEY,
    VISIT_TOKEN VARCHAR(50) UNIQUE NOT NULL,
    FULL_NAME VARCHAR(150) NOT NULL,
    MOBILE VARCHAR(15) NOT NULL,
    EMAIL VARCHAR(150),
    COMPANY_NAME VARCHAR(150),
    PURPOSE VARCHAR(500) NOT NULL,
    HOST_ID INT REFERENCES VMS_MASTER_HOST(HOST_ID),
    DEPT_ID INT REFERENCES VMS_MASTER_DEPT(DEPT_ID),
    EXPECTED_DATETIME TIMESTAMP NOT NULL,
    IDPROOF_TYPE_ID INT REFERENCES VMS_MASTER_IDPROOF(IDPROOF_ID),
    IDPROOF_NUMBER VARCHAR(50) NOT NULL,
    STATUS VARCHAR(20) DEFAULT 'Pending' CHECK (STATUS IN ('Pending', 'Approved', 'Checked-In', 'Checked-Out', 'Cancelled')),
    REGISTERED_BY INT REFERENCES VMS_USERS(USER_ID),
    CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE VMS_FILE_UPLOADS (
    FILE_ID SERIAL PRIMARY KEY,
    VISITOR_ID INT REFERENCES VMS_VISITORS(VISITOR_ID),
    UPLOAD_TYPE VARCHAR(50) CHECK (UPLOAD_TYPE IN ('Photo', 'IDProof')),
    ORIGINAL_NAME VARCHAR(255) NOT NULL,
    STORED_NAME VARCHAR(255) NOT NULL, 
    FILE_PATH VARCHAR(1000) NOT NULL,
    FILE_URL VARCHAR(1000) NOT NULL,
    FILE_SIZE_BYTES BIGINT,
    MIME_TYPE VARCHAR(50),
    UPLOADED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE VMS_CHECKIN_LOG (
    LOG_ID SERIAL PRIMARY KEY,
    VISITOR_ID INT REFERENCES VMS_VISITORS(VISITOR_ID),
    GATE_ID INT REFERENCES VMS_MASTER_GATE(GATE_ID),
    GUARD_ID INT REFERENCES VMS_USERS(USER_ID),
    CHECKIN_TIME TIMESTAMP NOT NULL,
    CHECKOUT_TIME TIMESTAMP,
    DURATION_MINUTES INT
);

CREATE TABLE VMS_AUDIT_LOG (
    AUDIT_ID SERIAL PRIMARY KEY,
    USER_ID INT REFERENCES VMS_USERS(USER_ID),
    ACTION_TYPE VARCHAR(100) NOT NULL,
    ENTITY_NAME VARCHAR(100),
    ENTITY_ID INT,
    IP_ADDRESS VARCHAR(50),
    ACTION_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    DETAILS TEXT
);

-- --------------------------------------------------------
-- 4. VIEWS
-- --------------------------------------------------------

CREATE OR REPLACE VIEW VW_VISITOR_FULL_DETAIL AS
SELECT 
    v.VISITOR_ID, v.VISIT_TOKEN, v.FULL_NAME, v.MOBILE, v.EMAIL, v.COMPANY_NAME, v.PURPOSE,
    v.EXPECTED_DATETIME, v.STATUS, v.IDPROOF_NUMBER,
    h.HOST_NAME, d.DEPT_NAME, p.PROOF_NAME as IDPROOF_TYPE,
    (SELECT FILE_URL FROM VMS_FILE_UPLOADS f WHERE f.VISITOR_ID = v.VISITOR_ID AND f.UPLOAD_TYPE = 'Photo' LIMIT 1) AS PHOTO_URL,
    (SELECT FILE_URL FROM VMS_FILE_UPLOADS f WHERE f.VISITOR_ID = v.VISITOR_ID AND f.UPLOAD_TYPE = 'IDProof' LIMIT 1) AS IDPROOF_URL,
    u.FULL_NAME AS REGISTERED_BY_NAME,
    v.DEPT_ID
FROM VMS_VISITORS v
LEFT JOIN VMS_MASTER_HOST h ON v.HOST_ID = h.HOST_ID
LEFT JOIN VMS_MASTER_DEPT d ON v.DEPT_ID = d.DEPT_ID
LEFT JOIN VMS_MASTER_IDPROOF p ON v.IDPROOF_TYPE_ID = p.IDPROOF_ID
LEFT JOIN VMS_USERS u ON v.REGISTERED_BY = u.USER_ID;

CREATE OR REPLACE VIEW VW_TODAY_VISITORS AS
SELECT * FROM VW_VISITOR_FULL_DETAIL
WHERE DATE(EXPECTED_DATETIME) = CURRENT_DATE;

CREATE OR REPLACE VIEW VW_ACTIVE_VISITORS AS
SELECT * FROM VW_VISITOR_FULL_DETAIL
WHERE STATUS = 'Checked-In';

-- --------------------------------------------------------
-- 5. SEED DATA
-- --------------------------------------------------------
INSERT INTO VMS_USERS (USERNAME, PASSWORD_HASH, FULL_NAME, ROLE, IS_ACTIVE)
VALUES ('ADMIN_01', '240be518fabd2724ddb6f04eeb1da5967448d7e831c08c8fa822809f74c720a9', 'System Administrator', 'ADMIN', 1)
ON CONFLICT DO NOTHING;
